# Generated by Django 3.1.6 on 2021-03-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.CharField(blank=True, max_length=512, null=True)),
                ('search_type', models.CharField(choices=[('submissions', 'Submissions'), ('comments', 'Comments')], default='submissions', max_length=11)),
                ('subreddit', models.CharField(blank=True, help_text='<br>comma separated: askreddit,askscience <br>Use ! to exclude: all,!askreddit', max_length=250, null=True)),
                ('syntax', models.CharField(choices=[('lucene', 'Lucene'), ('cloudsearch', 'Cloudsearch'), ('plain', 'Plain')], default='lucene', max_length=11)),
                ('limit', models.IntegerField(default=25)),
                ('praw_sort', models.CharField(blank=True, choices=[('relevance', 'Relevance'), ('hot', 'Hot'), ('top', 'Top'), ('new', 'New'), ('comments', 'Comments'), ('controversial', 'Controversial'), ('rising', 'Rising'), ('random_rising', 'Random Rising')], max_length=13, null=True)),
                ('time_filter', models.CharField(blank=True, choices=[('all', 'All Time'), ('hour', 'Past Hour'), ('day', 'Past 24 Hours'), ('month', 'Past Month'), ('year', 'Past Year')], max_length=5, null=True)),
                ('start_date', models.DateTimeField(blank=True, help_text='(M/D/YYYY)', null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('psaw_sort', models.CharField(blank=True, choices=[('created_utc', 'Date'), ('num_comments', 'Number of comments'), ('score', 'Score')], max_length=18, null=True)),
                ('date_created', models.DateField(auto_now=True)),
                ('favorite', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Search queries',
            },
        ),
    ]
