# Generated by Django 3.1.6 on 2021-03-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('last_clear_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
