# Generated by Django 3.1.6 on 2021-03-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='user',
            field=models.ForeignKey(default='redd_spider', on_delete=django.db.models.deletion.CASCADE, to='downloader.user'),
            preserve_default=False,
        ),
    ]
