# Generated by Django 3.1.6 on 2021-03-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_searchquery_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquery',
            name='search_type',
        ),
    ]
