# Generated by Django 3.1.6 on 2021-03-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0004_remove_searchquery_search_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
