# Generated by Django 3.1.6 on 2021-03-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0006_auto_20210318_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='url',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='subreddit',
            field=models.CharField(blank=True, help_text='Comma separated: askreddit,askscience <br>Use ! to exclude: all,!askreddit', max_length=250),
        ),
    ]
