# Generated by Django 3.1.6 on 2021-03-28 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0007_auto_20210324_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='(YYYY-MM-DD [HH:MM:SS])', null=True),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='downloader.user'),
        ),
    ]
